### ISSUE TITLE
[QUESTION] How are we funding the contract with LINK if we are on ganache?

### ISSUE THREAD

**Issue by Magofoco** [PatrickAlphaC/smartcontract-lottery#3]
In our **tests** folder we have the following code:

```
def test_can_end_lottery():
    if network.show_active() not in LOCAL_BLOCKCHAIN_ENVIRONMENTS:
        pytest.skip()
    lottery = deploy_lottery()
    account = get_account()
    lottery.startLottery({"from": account})
    lottery.enter({"from": account, "value": lottery.getEntranceFee()})
    fund_with_link(lottery) <------- HERE IS THE FUNCTION I WANT TO ASK ABOUT
    lottery.endLottery({"from": account})
    assert lottery.lottery_state() == 2
```

which calls the function `fund_with_link(lottery)`. This function should fund our contract with LINK.

When we tun our tests:
`brownie test -k test_can_end_lottery `
we use the development network which, if I understood correctly, is **ganache** because brownie spins a local ganache for us.

**QUESTION**
How can we fund our contract with LINK if we use the account which is in the development network (ganache)? I mean, the account[0] in ganache should have ZERO link.
Why is not the test failing?
Does ganache have a notion of CHAINLINK?

**Comment by PatrickAlphaC** [comment]
Great question :)

The answer, is with "mocking"

We do some clever stuff to make sure our tests pass even when working with ganache. In order to fund with LINK we need a LINK ERC677 contract. But there isn't one on ganache, so we deploy a "mock" one, or a "dummy" LINK token contract.

https://github.com/PatrickAlphaC/smartcontract-lottery/blob/8876d504b707883f148f9a8cac7a287b90d0f5df/scripts/helpful_scripts.py#L39

We "get" the LINK contract by calling `get_contract`, which will do one of 2 things:

1. If the contract exists (like on a testnet) grab the address of the token from the config.
2. If not (like in ganache) deploy a fake token, and use that for the duration of the tests.

Let me know if that isn't clear!
