### ISSUE TITLE
 Fail - Unable to verify

### ISSUE THREAD

**Issue by amazzuca** [PatrickAlphaC/smartcontract-lottery#52]
I'm deploying to rinkeby network using:

**brownie run deploy_lottery.py --network rinkeby.**

It does everything Ok but the following error:

**Verification complete. Result: Fail - Unable to verify**

And also, at the end:
**lottery Ended!!
0x0000000000000000000000000000000000000000 is the winner!**

Why I cannot verify the contract?

**Comment by PatrickAlphaC** [comment]
Rinkeby was having issues. Please try again thanks.

**Comment by gianfra-t** [comment]
I am having the same issue. I believe that it could be because time.sleep(60) is not enough time for the Chainlink node to respond with the random value. So we are reading the values in the assert before it actually executes the winner picking part.
At least in my case, after some time in etherscan it shows that the winner my account.

**Comment by PatrickAlphaC** [comment]
Yes, please wait longer.
